### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by AllanLRH** [alkuzad/CloseMinimapOnMultiView#1]
Scenario:
* I have two files opened in two tabs, and the minimap is on.
* I move the rightmost tab to a pane created on the right, and the minimaps persist, albeit narrower.

It doesn't matter whether I'm moving the file using the build in function or the wonderful Origami-plugin (which seems to call `command: carry_file_to_pane {"direction": "right"}`), or by selecting "View" → "Groups" → "Move File to New Group" (which seems to call `command: new_pane
`).

**Comment by alkuzad** [comment]
Hi @AllanLRH  thanks for this issue :) Plugin is monitoring window event called set_layout which is used to when setting layout manually. I really never used groups, but indeed it's a bug.

I released v0.2.0, can you try it ? I usually debug my plugins locally using OpenResource as beta channel in PackageControl needs user intervention

**Comment by alkuzad** [comment]
@AllanLRH Closed due to no response

**Comment by AllanLRH** [comment]
Sorry, I forgot all about it.
I just reinstalled the plugin directly from the Git repo, and "View" → "Groups" → "Move File to New Group" seems to be working.
Moving a file to a new panel (which is automatically created) are unfortunately not working — it's how I usually manages my layouts.

**Comment by alkuzad** [comment]
@AllanLRH thanks for response :)

**Comment by alkuzad** [comment]
Yep, seems that window.set_layout (which is undocumented) does not send event, there is easy workaround using window.run_command though.

Let's see what Jon && Wbond thinks about that: https://forum.sublimetext.com/t/window-set-layout-does-not-send-window-command-event-set-layout/34361

If it's intended then I will speak to Origami author if he can modify code on his side.

**Comment by alkuzad** [comment]
So bug is added to ST issues github and being discussed on forum. 

@AllanLRH You can try applying this [gist](https://gist.github.com/alkuzad/7fff717bf5d5503f50299a242b6e02ec). You can do it by OpenResource plugin - open origami.py and change all `window.set_layout` commands to run_command ones. This should fix problem but I would like to discuss this with ST devs if API should be changed.

**Comment by AllanLRH** [comment]
I made the suggested edits (but I think the plugin you're thinking of are called [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer)?), and that seems to fix the problem.
The minimap are hidden when the number of panels go from 1 → 2, and it's reenabled when the new panel are destroyed.

But I can't help but to suggest another improvement: Only hide the minimap when a new panel are created in a side-by-side view, not in a above-and-below view, because there's no shortage of horizontal space in the latter case.
But I think it's a minor gripe, as I 95 % of the time use the side-by-side layout when I use multiple panels ☺︎

**Comment by alkuzad** [comment]
@AllanLRH great it's working :)

It's easy to react only for columns - plugin uses 'cells' list which lists all cells boundaries. I can change it to `cols` and it will react only for new columns.

I think this should be configurable so I will make something better but if you want this [gist](https://gist.github.com/alkuzad/f3051a9fe5e37a91ba195df448a828ce) should work. I will add some settings parsing and default settings to have this configurable (old and new, default will be new way)

**Comment by alkuzad** [comment]
I pushed new version which uses cols by default and provides setting to change that.

However Origami problem is still on the table @adzenith will you consider merging simple PR which changes window.set_layout to window.run_command('set_layout') ?

**Comment by adzenith** [comment]
Sure, send it and I'll take a look! Sounds simple enough.

**Comment by alkuzad** [comment]
So @AllanLRH SublimeText/Origami#132 is opened and if it will be merged (by @adzenith) this ticket will be completely solved. I'm closing this one as nothing depends on me right now.

**Comment by adzenith** [comment]
Merged! Thanks for the contribution.
